[phases.setup]
nixPkgs = ["php84", "php84Extensions.intl", "php84Extensions.pdo_mysql", "php84Extensions.mbstring", "php84Extensions.zip"]

[phases.install]
cmds = ["composer install --no-interaction --optimize-autoloader"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t webroot"